openapi: 3.0.0
info:
  title: Quiz Master API
  description: REST API for the Quiz Master application
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
        name:
          type: string
        role:
          type: array
          items:
            type: string
    
    Subject:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        quizCount:
          type: integer
        chapterCount:
          type: integer
    
    Chapter:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        subject_id:
          type: integer
        quizCount:
          type: integer
    
    Quiz:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        difficulty:
          type: string
          enum: [Easy, Medium, Hard]
        duration:
          type: integer
        chapter_id:
          type: integer
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        questionCount:
          type: integer
    
    Question:
      type: object
      properties:
        id:
          type: integer
        question:
          type: string
        option1:
          type: string
        option2:
          type: string
        option3:
          type: string
        option4:
          type: string
        correct_option:
          type: integer
          minimum: 1
          maximum: 4
        quiz_id:
          type: integer

    QuizAttempt:
      type: object
      properties:
        quiz_id:
          type: integer
        answers:
          type: object
        time_spent:
          type: integer
        score:
          type: number
        totalQuestions:
          type: integer
        correctAnswers:
          type: integer
        status:
          type: string
          enum: [Passed, Failed]

paths:
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  role:
                    type: string
                  email:
                    type: string
                  username:
                    type: string

  /register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        '200':
          description: Registration successful

  /subjects:
    get:
      summary: Get all subjects
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of subjects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'

  /create_subject:
    post:
      summary: Create a new subject
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        '201':
          description: Subject created successfully

  /quizzes/{chapter_id}:
    get:
      summary: Get quizzes for a chapter
      security:
        - bearerAuth: []
      parameters:
        - name: chapter_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of quizzes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'

  /create_quiz:
    post:
      summary: Create a new quiz
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '201':
          description: Quiz created successfully

  /get_ques/{quiz_id}:
    get:
      summary: Get questions for a quiz
      security:
        - bearerAuth: []
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of questions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'

  /add_que/{quiz_id}:
    post:
      summary: Add a question to a quiz
      security:
        - bearerAuth: []
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '201':
          description: Question added successfully

  /submit_quiz:
    post:
      summary: Submit a quiz attempt
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuizAttempt'
      responses:
        '201':
          description: Quiz submitted successfully

  /get_attempts:
    get:
      summary: Get user's quiz attempts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of quiz attempts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    quiz_id:
                      type: integer
                    name:
                      type: string
                    subject:
                      type: string
                    questions:
                      type: integer
                    score:
                      type: number
                    date:
                      type: string
                      format: date-time
                    status:
                      type: string
                    timespent:
                      type: integer

  /user/summary:
    get:
      summary: Get user's performance summary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User performance summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_quizzes:
                    type: integer
                  average_score:
                    type: number
                  quizzes_this_month:
                    type: integer
                  best_subject:
                    type: string
                  subject_performance:
                    type: object
                  monthly_activity:
                    type: array
                    items:
                      type: object
                      properties:
                        month:
                          type: string
                        count:
                          type: integer
                  recent_quizzes:
                    type: array
                    items:
                      type: object